<template><div><h1 id="basic-arithmetics" tabindex="-1"><a class="header-anchor" href="#basic-arithmetics"><span>Basic Arithmetics</span></a></h1>
<p>Openmadness makes performing common math operations on lists of numbers (which we call arrays) super easy. Instead of performing calculations one by one, Openmadness lets you apply operations to entire arrays at once.</p>
<p>When you use an arithmetic method like add() or multiply() on an Openmadness array, it applies that operation to every corresponding number in the array. If you add a single number (a scalar), it's added to every element in the array.</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> om <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Create Openmadness arrays</span></span>
<span class="line"><span class="token keyword">const</span> dailySales <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">100</span><span class="token punctuation">,</span> <span class="token number">150</span><span class="token punctuation">,</span> <span class="token number">200</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> marketingSpend <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token number">40</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Daily Sales:"</span><span class="token punctuation">,</span> dailySales<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Marketing Spend:"</span><span class="token punctuation">,</span> marketingSpend<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// --- Addition (+) ---</span></span>
<span class="line"><span class="token comment">// Add two arrays (element-wise)</span></span>
<span class="line"><span class="token keyword">const</span> totalRevenue <span class="token operator">=</span> dailySales<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span>marketingSpend<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Total Revenue (Sales + Spend):"</span><span class="token punctuation">,</span> totalRevenue<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [110, 175, 240]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Add a scalar to an array</span></span>
<span class="line"><span class="token keyword">const</span> salesIncrease <span class="token operator">=</span> dailySales<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token number">50</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Sales after $50 increase:"</span><span class="token punctuation">,</span> salesIncrease<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [150, 200, 250]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// --- Subtraction (-) ---</span></span>
<span class="line"><span class="token keyword">const</span> netSales <span class="token operator">=</span> dailySales<span class="token punctuation">.</span><span class="token function">subtract</span><span class="token punctuation">(</span>marketingSpend<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Net Sales (Sales - Spend):"</span><span class="token punctuation">,</span> netSales<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [90, 125, 160]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// --- Multiplication (*) ---</span></span>
<span class="line"><span class="token keyword">const</span> doubledSales <span class="token operator">=</span> dailySales<span class="token punctuation">.</span><span class="token function">multiply</span><span class="token punctuation">(</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Doubled Sales:"</span><span class="token punctuation">,</span> doubledSales<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [200, 300, 400]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// --- Division (/) ---</span></span>
<span class="line"><span class="token keyword">const</span> salesRatio <span class="token operator">=</span> dailySales<span class="token punctuation">.</span><span class="token function">divide</span><span class="token punctuation">(</span>marketingSpend<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Sales Ratio (Sales / Spend):"</span><span class="token punctuation">,</span> salesRatio<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [10, 6, 5]</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


