<template><div><h1 id="logical-operations" tabindex="-1"><a class="header-anchor" href="#logical-operations"><span>Logical Operations</span></a></h1>
<p>OpenMadness provides powerful comparison methods that let you evaluate conditions across your data. These operations create boolean arrays (arrays of true/false values) that you can use for filtering, masking, or further analysis.</p>
<h2 id="comparison-operations" tabindex="-1"><a class="header-anchor" href="#comparison-operations"><span>Comparison Operations</span></a></h2>
<h3 id="greater-than-and-less-than" tabindex="-1"><a class="header-anchor" href="#greater-than-and-less-than"><span>Greater Than and Less Than</span></a></h3>
<p>Compare each element against a threshold value:</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> omArray<span class="token punctuation">,</span> greaterThan<span class="token punctuation">,</span> lessThan <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> temperatures <span class="token operator">=</span> <span class="token function">omArray</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">68</span><span class="token punctuation">,</span> <span class="token number">75</span><span class="token punctuation">,</span> <span class="token number">62</span><span class="token punctuation">,</span> <span class="token number">83</span><span class="token punctuation">,</span> <span class="token number">71</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Temperatures:"</span><span class="token punctuation">,</span> temperatures<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// Output: [68, 75, 62, 83, 71]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Check which temperatures are above 70°F</span></span>
<span class="line"><span class="token keyword">const</span> isHot <span class="token operator">=</span> temperatures<span class="token punctuation">.</span><span class="token function">greaterThan</span><span class="token punctuation">(</span><span class="token number">70</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Above 70°F:"</span><span class="token punctuation">,</span> isHot<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// Output: [false, true, false, true, true]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Check which temperatures are below 65°F</span></span>
<span class="line"><span class="token keyword">const</span> isCool <span class="token operator">=</span> temperatures<span class="token punctuation">.</span><span class="token function">lessThan</span><span class="token punctuation">(</span><span class="token number">65</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Below 65°F:"</span><span class="token punctuation">,</span> isCool<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// Output: [false, false, true, false, false]</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="equal-and-not-equal" tabindex="-1"><a class="header-anchor" href="#equal-and-not-equal"><span>Equal and Not Equal</span></a></h3>
<p>Test for exact matches or differences:</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> omArray<span class="token punctuation">,</span> equal<span class="token punctuation">,</span> notEqual <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> statusCodes <span class="token operator">=</span> <span class="token function">omArray</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">200</span><span class="token punctuation">,</span> <span class="token number">404</span><span class="token punctuation">,</span> <span class="token number">200</span><span class="token punctuation">,</span> <span class="token number">500</span><span class="token punctuation">,</span> <span class="token number">200</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Status Codes:"</span><span class="token punctuation">,</span> statusCodes<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// Output: [200, 404, 200, 500, 200]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Find all successful responses (code 200)</span></span>
<span class="line"><span class="token keyword">const</span> isSuccess <span class="token operator">=</span> statusCodes<span class="token punctuation">.</span><span class="token function">equal</span><span class="token punctuation">(</span><span class="token number">200</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Success responses:"</span><span class="token punctuation">,</span> isSuccess<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// Output: [true, false, true, false, true]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Find all error responses (not 200)</span></span>
<span class="line"><span class="token keyword">const</span> isError <span class="token operator">=</span> statusCodes<span class="token punctuation">.</span><span class="token function">notEqual</span><span class="token punctuation">(</span><span class="token number">200</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Error responses:"</span><span class="token punctuation">,</span> isError<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// Output: [false, true, false, true, false]</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="greater-less-than-or-equal" tabindex="-1"><a class="header-anchor" href="#greater-less-than-or-equal"><span>Greater/Less Than or Equal</span></a></h3>
<p>Include the threshold value in your comparison:</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> omArray<span class="token punctuation">,</span> greaterThanOrEqual<span class="token punctuation">,</span> lessThanOrEqual <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> scores <span class="token operator">=</span> <span class="token function">omArray</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">85</span><span class="token punctuation">,</span> <span class="token number">90</span><span class="token punctuation">,</span> <span class="token number">70</span><span class="token punctuation">,</span> <span class="token number">95</span><span class="token punctuation">,</span> <span class="token number">60</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Test Scores:"</span><span class="token punctuation">,</span> scores<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// Output: [85, 90, 70, 95, 60]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Check which scores are at least 70 (passing)</span></span>
<span class="line"><span class="token keyword">const</span> isPassing <span class="token operator">=</span> scores<span class="token punctuation">.</span><span class="token function">greaterThanOrEqual</span><span class="token punctuation">(</span><span class="token number">70</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Passing scores:"</span><span class="token punctuation">,</span> isPassing<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// Output: [true, true, true, true, false]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Check which scores are at most 85 (need improvement)</span></span>
<span class="line"><span class="token keyword">const</span> needsImprovement <span class="token operator">=</span> scores<span class="token punctuation">.</span><span class="token function">lessThanOrEqual</span><span class="token punctuation">(</span><span class="token number">85</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Scores needing improvement:"</span><span class="token punctuation">,</span> needsImprovement<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// Output: [true, false, true, false, true]</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="combining-logical-operations" tabindex="-1"><a class="header-anchor" href="#combining-logical-operations"><span>Combining Logical Operations</span></a></h2>
<p>You can chain logical operations to create complex conditions:</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> omArray<span class="token punctuation">,</span> and<span class="token punctuation">,</span> greaterThan<span class="token punctuation">,</span> lessThan <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> values <span class="token operator">=</span> <span class="token function">omArray</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">15</span><span class="token punctuation">,</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token number">35</span><span class="token punctuation">,</span> <span class="token number">45</span><span class="token punctuation">,</span> <span class="token number">55</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Values:"</span><span class="token punctuation">,</span> values<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// Output: [15, 25, 35, 45, 55]</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// Find values between 20 and 50</span></span>
<span class="line"><span class="token keyword">const</span> greaterThan20 <span class="token operator">=</span> values<span class="token punctuation">.</span><span class="token function">greaterThan</span><span class="token punctuation">(</span><span class="token number">20</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> lessThan50 <span class="token operator">=</span> values<span class="token punctuation">.</span><span class="token function">lessThan</span><span class="token punctuation">(</span><span class="token number">50</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> between20And50 <span class="token operator">=</span> greaterThan20<span class="token punctuation">.</span><span class="token function">and</span><span class="token punctuation">(</span>lessThan50<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Between 20 and 50:"</span><span class="token punctuation">,</span> between20And50<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// Output: [false, true, true, true, false]</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="using-logical-results" tabindex="-1"><a class="header-anchor" href="#using-logical-results"><span>Using Logical Results</span></a></h2>
<h3 id="counting-true-values" tabindex="-1"><a class="header-anchor" href="#counting-true-values"><span>Counting True Values</span></a></h3>
<p>Count how many elements meet your condition:</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> omArray<span class="token punctuation">,</span> greaterThanOrEqual <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> ages <span class="token operator">=</span> <span class="token function">omArray</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">17</span><span class="token punctuation">,</span> <span class="token number">22</span><span class="token punctuation">,</span> <span class="token number">16</span><span class="token punctuation">,</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token number">19</span><span class="token punctuation">,</span> <span class="token number">30</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> isAdult <span class="token operator">=</span> ages<span class="token punctuation">.</span><span class="token function">greaterThanOrEqual</span><span class="token punctuation">(</span><span class="token number">18</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Is adult:"</span><span class="token punctuation">,</span> isAdult<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// Output: [false, true, false, true, true, true]</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> adultCount <span class="token operator">=</span> isAdult<span class="token punctuation">.</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Number of adults:"</span><span class="token punctuation">,</span> adultCount<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// Output: 4</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="filtering-with-logical-arrays" tabindex="-1"><a class="header-anchor" href="#filtering-with-logical-arrays"><span>Filtering with Logical Arrays</span></a></h3>
<p>Use logical arrays to extract matching elements:</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> omArray<span class="token punctuation">,</span> lessThan<span class="token punctuation">,</span> filter <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> prices <span class="token operator">=</span> <span class="token function">omArray</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">12.99</span><span class="token punctuation">,</span> <span class="token number">8.50</span><span class="token punctuation">,</span> <span class="token number">15.75</span><span class="token punctuation">,</span> <span class="token number">9.99</span><span class="token punctuation">,</span> <span class="token number">22.50</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">const</span> isBudget <span class="token operator">=</span> prices<span class="token punctuation">.</span><span class="token function">lessThan</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Budget items:"</span><span class="token punctuation">,</span> isBudget<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// Output: [false, true, false, true, false]</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> budgetPrices <span class="token operator">=</span> prices<span class="token punctuation">.</span><span class="token function">filter</span><span class="token punctuation">(</span>isBudget<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Budget prices:"</span><span class="token punctuation">,</span> budgetPrices<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// Output: [8.50, 9.99]</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


