<template><div><h1 id="shape" tabindex="-1"><a class="header-anchor" href="#shape"><span>Shape</span></a></h1>
<p>The shape of an Openmadness array describes its dimensions or structure. Think of it as how your data is organized – like the rows and columns of a spreadsheet.</p>
<ul>
<li>A simple list of numbers has one dimension.</li>
<li>A table of numbers has two dimensions (rows and columns).
The shape property returns an array indicating the size of each dimension.</li>
</ul>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> om <span class="token keyword">from</span> <span class="token string">'openmadness'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token comment">// A 1-dimensional array (like a single list)</span></span>
<span class="line"><span class="token keyword">const</span> dailyVisitors <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token number">1000</span><span class="token punctuation">,</span> <span class="token number">1200</span><span class="token punctuation">,</span> <span class="token number">950</span><span class="token punctuation">,</span> <span class="token number">1300</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Daily Visitors data:"</span><span class="token punctuation">,</span> dailyVisitors<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Shape of Daily Visitors:"</span><span class="token punctuation">,</span> dailyVisitors<span class="token punctuation">.</span>shape<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [4]</span></span>
<span class="line"><span class="token comment">// It has 4 elements in its single dimension.</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// A 2-dimensional array (like a grid or table)</span></span>
<span class="line"><span class="token keyword">const</span> quarterlySales <span class="token operator">=</span> om<span class="token punctuation">.</span><span class="token function">array</span><span class="token punctuation">(</span><span class="token punctuation">[</span></span>
<span class="line">    <span class="token punctuation">[</span><span class="token number">100</span><span class="token punctuation">,</span> <span class="token number">120</span><span class="token punctuation">,</span> <span class="token number">90</span><span class="token punctuation">]</span><span class="token punctuation">,</span>  <span class="token comment">// Q1 sales for 3 regions</span></span>
<span class="line">    <span class="token punctuation">[</span><span class="token number">110</span><span class="token punctuation">,</span> <span class="token number">130</span><span class="token punctuation">,</span> <span class="token number">95</span><span class="token punctuation">]</span><span class="token punctuation">,</span>  <span class="token comment">// Q2 sales for 3 regions</span></span>
<span class="line">    <span class="token punctuation">[</span><span class="token number">105</span><span class="token punctuation">,</span> <span class="token number">125</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">]</span>  <span class="token comment">// Q3 sales for 3 regions</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"\nQuarterly Sales data:\n"</span><span class="token punctuation">,</span> quarterlySales<span class="token punctuation">.</span>data<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">"Shape of Quarterly Sales:"</span><span class="token punctuation">,</span> quarterlySales<span class="token punctuation">.</span>shape<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Output: [3, 3]</span></span>
<span class="line"><span class="token comment">// This means 3 rows and 3 columns.</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Understanding shape is crucial because many operations require arrays to have compatible shapes.</p>
</div></template>


